### PR TITLE
Update: 1) Upper Drive Frames: BOM screws + tool holes 2) XY-Joints: Clearance for bearing stacks

### PR DESCRIPTION
**Pull request by Finn2708**
Changes: 
- **A Drive Frame Upper:**
  - Added tool hole for access to 4th motor screw
  - Modified Y end stop feature so BOM screws do not protrude top face
  - Added M2x10 self tapping screws

- **B Drive Frame Upper:**
  - Added tool hole for access to 4th motor screw

- **X Axis:**
  - Entire assemble was offset 1mm to the front. Should be fixed now.

### CODE REVIEW

**Comment by hartk1213** [comment]
would you want to export the STLs to go along with those and make sure they are oriented correctly for printing? should just be the to upper motor plates on the A and B drives

**Comment by Finn2708** [comment]
Yeah, that would make sense. I can't update the pin mod files though, as I don't have CAD data for that.

**Comment by Finn2708** [comment]
I updated the `A Drive Frame Upper` STLs in the KGLM and RC folders.

**Comment by hartk1213** [comment]
> Yeah, that would make sense. I can't update the pin mod files though, as I don't have CAD data for that.

https://github.com/Finn2708/Micron/tree/main/CAD/pinned-gantry

you should have it there...and also thanks for this man huge help!

**Comment by Finn2708** [comment]
Alright, I updated the pinned versions as well. 

I also took the liberty to fix the XY-Joints to provide proper clearance to the bearing stacks.

**Comment by hartk1213** [comment]
perfect! thanks man!

**Pull request merged**
